version: 2.1
orbs:
  node: circleci/node@4.0.0

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    macos:
      xcode: 11.0.0
    steps:
      - node/install:
          node-version: "14.11.0"
      - checkout:
      -run:
          name: checkout
          command: checkout
      - run:
          name: clean
          command: ls
      - run:
          name: install project
          command: npm install
      - run:
          name: build project
          command: npm run build
      