version: 2.1
orbs:
  node: circleci/node:14.21.2-browsers

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: clean
          command: ls
      - run:
          name : set up version
          command:  nvm use 14
      - run:
          name: install project
          command: npm install
      - run:
          name: build project
          command: npm run build
      