version: 2.1
orbs:
  node: circleci/node@5.1.0
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: clean
          command: ls
      - run:
          name : set up version
          command:  nvm install 14
      - run:
          name: install project
          command: python -- version && brew install python@3.8 && nvm use 14 && npm install
      - run:
          name: build project
          command: npm run build
      