version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:14.21.2
    steps:
      - checkout
      - run:
          name: clean
          command: ls
      - run:
          name: install project
          command: npm install
      - run:
          name: build project
          command: npm run build
      