version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:14.16.3
    steps:
      - checkout
      - run:
          name: clean
          command: ls
      - run:
          name: change node version
          command: nvm use 14
      - run:
          name: install project
          command: npm install
      - run:
          name: build project
          command: npm run build
      