version: 2.1
orbs:
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: clean
          command: ls
      - run:
          name : set up version
          command:  nvm install 14
      - run:
          name: python version
          command : python3 --version 
      - run:
          name: install project
          command: brew install pyenv && brew install python@3.10 && pyenv global 3.10 && nvm use 14 && npm install
      - run:
          name: build project
          command: npm run build
      